In [30]:
def n_queens(n):
    def is_valid(queens, new_queen):
        for row, col in enumerate(queens):
            if col == new_queen:
                return False
        return True

    def solve(queens):
        if len(queens) == n:
            board = [[0] * n for _ in range(n)]
            for i, j in enumerate(queens):
                board[i][j] = 1
            results.append(board)
            return
        for i in range(n):
            if is_valid(queens, i):
                solve(queens + [i])

    results = []
    solve([])

    return results

n = 7
solutions = n_queens(n)


In [31]:
import numpy as np

B = np.zeros((7, 7))
print(B)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [32]:
A = [
    [2, 4, 3, 6 ,7, 1, 4], #Dan
    [7, 3, 2, 6, 5, 4, 1], #Ari
    [7, 3, 6, 4, 5, 2, 1], #Mark
    [0, 0, 0, 0, 0, 0, 7], #Luka
    [4, 1, 7, 6, 5, 3, 2], #Zach
    [0, 0, 7, 0, 0, 0, 0], #Jared
    [6, 7, 5, 4, 3, 2, 1]  #Isaiah
]

solutions = n_queens(n)

movingcount=0
holdingcount=0

def dot_product(a, b):
    if len(a) != len(b):
        raise ValueError("Both lists should be of the same length")

    return sum(x*y for x, y in zip(a, b))

In [33]:
solutions = n_queens(n)
for sol in solutions:
    movingcount = 0
    i=0
    for row in sol:
        B[i]=row
        movingcount = movingcount + dot_product(row,A[i])
        i=i+1
    #print("------")         
    #print ("current sum is:  ", movingcount)
    if movingcount>holdingcount or movingcount>40:
        holdingcount = movingcount
        print (B)
        print("------")#
        print ("holding count is now:  ", holdingcount, "\n")
        
print ("Final holding count is:  ", holdingcount, "  Find corresponding solution")   

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
------
holding count is now:   17 

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]]
------
holding count is now:   18 

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]]
------
holding count is now:   19 

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]]
------
holding count is now:   20 

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]
------
hold